create table public.stat_kch_install_retention_count
(
	bj_date varchar(16),
	app_name varchar(64),
	media_source varchar(32) default 'null'::character varying,
	facebook_account_id varchar(64) default 'null'::character varying,
	facebook_adset varchar(255) default 'null'::character varying,
	creative varchar(255) default 'null'::character varying,
	source_id varchar(255) default 'null'::character varying,
	country varchar(8) default 'null'::character varying,
	install_count integer encode az64,
	retention_1d_count integer encode az64,
	retention_2d_count integer encode az64,
	retention_3d_count integer encode az64,
	retention_7d_count integer encode az64,
	retention_4d_count integer encode az64,
	retention_5d_count integer encode az64,
	retention_6d_count integer encode az64,
	retention_8d_count integer encode az64,
	retention_9d_count integer encode az64,
	retention_10d_count integer encode az64,
	retention_11d_count integer encode az64,
	retention_12d_count integer encode az64,
	retention_13d_count integer encode az64,
	retention_14d_count integer encode az64,
	retention_15d_count integer encode az64,
	retention_16d_count integer encode az64,
	retention_17d_count integer encode az64,
	retention_18d_count integer encode az64,
	retention_19d_count integer encode az64,
	retention_20d_count integer encode az64,
	retention_21d_count integer encode az64,
	retention_22d_count integer encode az64,
	retention_23d_count integer encode az64,
	retention_24d_count integer encode az64,
	retention_25d_count integer encode az64,
	retention_26d_count integer encode az64,
	retention_27d_count integer encode az64,
	retention_28d_count integer encode az64,
	retention_29d_count integer encode az64,
	retention_30d_count integer encode az64,
	retention_31d_count integer encode az64,
	retention_32d_count integer encode az64,
	retention_33d_count integer encode az64,
	retention_34d_count integer encode az64,
	retention_35d_count integer encode az64,
	retention_36d_count integer encode az64,
	retention_37d_count integer encode az64,
	retention_38d_count integer encode az64,
	retention_39d_count integer encode az64,
	retention_40d_count integer encode az64,
	retention_41d_count integer encode az64,
	retention_42d_count integer encode az64,
	retention_43d_count integer encode az64,
	retention_44d_count integer encode az64,
	retention_45d_count integer encode az64,
	retention_46d_count integer encode az64,
	retention_47d_count integer encode az64,
	retention_48d_count integer encode az64,
	retention_49d_count integer encode az64,
	retention_50d_count integer encode az64,
	retention_51d_count integer encode az64,
	retention_52d_count integer encode az64,
	retention_53d_count integer encode az64,
	retention_54d_count integer encode az64,
	retention_55d_count integer encode az64,
	retention_56d_count integer encode az64,
	retention_57d_count integer encode az64,
	retention_58d_count integer encode az64,
	retention_59d_count integer encode az64,
	retention_60d_count integer encode az64,
	campaign_id varchar(64),
	retention_90d_count integer encode az64,
	retention_1d_muid_count integer encode az64,
	retention_2d_muid_count integer encode az64,
	retention_3d_muid_count integer encode az64,
	retention_4d_muid_count integer encode az64,
	retention_5d_muid_count integer encode az64,
	retention_6d_muid_count integer encode az64,
	retention_7d_muid_count integer encode az64,
	retention_8d_muid_count integer encode az64,
	retention_9d_muid_count integer encode az64,
	retention_10d_muid_count integer encode az64,
	retention_11d_muid_count integer encode az64,
	retention_12d_muid_count integer encode az64,
	retention_13d_muid_count integer encode az64,
	retention_14d_muid_count integer encode az64,
	retention_15d_muid_count integer encode az64,
	retention_16d_muid_count integer encode az64,
	retention_17d_muid_count integer encode az64,
	retention_18d_muid_count integer encode az64,
	retention_19d_muid_count integer encode az64,
	retention_20d_muid_count integer encode az64,
	retention_21d_muid_count integer encode az64,
	retention_22d_muid_count integer encode az64,
	retention_23d_muid_count integer encode az64,
	retention_24d_muid_count integer encode az64,
	retention_25d_muid_count integer encode az64,
	retention_26d_muid_count integer encode az64,
	retention_27d_muid_count integer encode az64,
	retention_28d_muid_count integer encode az64,
	retention_29d_muid_count integer encode az64,
	retention_30d_muid_count integer encode az64,
	retention_31d_muid_count integer encode az64,
	retention_32d_muid_count integer encode az64,
	retention_33d_muid_count integer encode az64,
	retention_34d_muid_count integer encode az64,
	retention_35d_muid_count integer encode az64,
	retention_36d_muid_count integer encode az64,
	retention_37d_muid_count integer encode az64,
	retention_38d_muid_count integer encode az64,
	retention_39d_muid_count integer encode az64,
	retention_40d_muid_count integer encode az64,
	retention_41d_muid_count integer encode az64,
	retention_42d_muid_count integer encode az64,
	retention_43d_muid_count integer encode az64,
	retention_44d_muid_count integer encode az64,
	retention_45d_muid_count integer encode az64,
	retention_46d_muid_count integer encode az64,
	retention_47d_muid_count integer encode az64,
	retention_48d_muid_count integer encode az64,
	retention_49d_muid_count integer encode az64,
	retention_50d_muid_count integer encode az64,
	retention_51d_muid_count integer encode az64,
	retention_52d_muid_count integer encode az64,
	retention_53d_muid_count integer encode az64,
	retention_54d_muid_count integer encode az64,
	retention_55d_muid_count integer encode az64,
	retention_56d_muid_count integer encode az64,
	retention_57d_muid_count integer encode az64,
	retention_58d_muid_count integer encode az64,
	retention_59d_muid_count integer encode az64,
	retention_60d_muid_count integer encode az64,
	retention_90d_muid_count integer encode az64,
	install_muid_count integer encode az64
)
sortkey(bj_date);

alter table public.stat_kch_install_retention_count owner to awsuser;

grant select on public.stat_kch_install_retention_count to gv_ro;

grant select on public.stat_kch_install_retention_count to gv_online_ro;

grant delete, insert, references, select, trigger, update on public.stat_kch_install_retention_count to gv_online_rw;

grant select on public.stat_kch_install_retention_count to gv_offline_ro;

grant delete, insert, references, select, trigger, update on public.stat_kch_install_retention_count to gv_offline_rw;

grant select on public.stat_kch_install_retention_count to gv_alert;

grant select on public.stat_kch_install_retention_count to dev_user;

