chapter_list_local = """
{
    "msg":"操作成功",
    "retval":[
        {
            "id":425,
            "name":"序",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":51196,
            "read_info":{
                "last_update_sign":"\/epub\/86828969\/OEBPS\/Text\/chapter0.xhtml"
            }
        },
        {
            "id":426,
            "name":"前言",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":28550,
            "read_info":{
                "last_update_sign":"\/epub\/86828969\/OEBPS\/Text\/chapter0_0001.xhtml"
            }
        },
        {
            "id":427,
            "name":"一、中国经济进入新时代",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/Section0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":27149,
            "read_info":{
                "last_update_sign":"\/epub\/86828969\/OEBPS\/Text\/Section0001.xhtml"
            }
        },
        {
            "id":428,
            "name":"二、这十年经济发展的新成就",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/Section0002.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":23724,
            "read_info":{
                "last_update_sign":"\/epub\/86828969\/OEBPS\/Text\/Section0002.xhtml"
            }
        },
        {
            "id":429,
            "name":"三、这十年经济发展的新特点和新经验",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/Section0003.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":26763,
            "read_info":{
                "last_update_sign":"\/epub\/86828969\/OEBPS\/Text\/Section0003.xhtml"
            }
        },
        {
            "id":430,
            "name":"四、这十年经济发展的历史意义",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/Section0004.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":24647,
            "read_info":{
                "last_update_sign":"\/epub\/86828969\/OEBPS\/Text\/Section0004.xhtml"
            }
        },
        {
            "id":431,
            "name":"第一章 引领新时代的习近平经济思想",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0_0001_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":16878,
            "read_info":{
                "last_update_sign":"\/epub\/86828969\/OEBPS\/Text\/chapter0_0001_0001.xhtml"
            }
        },
        {
            "id":432,
            "name":"第一节党领导的以人民为中心的发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":15426,
            "read_info":{
                "last_update_sign":"\/epub\/86828969\/OEBPS\/Text\/chapter0-0.xhtml"
            }
        },
        {
            "id":433,
            "name":"一、加强党对经济工作的全面领导",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-0-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":15355,
            "read_info":{
                "last_update_sign":""
            }
        },
        {
            "id":434,
            "name":"二、坚持以人民为中心的发展思想",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-0-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":15114,
            "read_info":{

            }
        },
        {
            "id":435,
            "name":"三、准确把握历史方位与社会主要矛盾变化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-0-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":14376,
            "read_info":{

            }
        },
        {
            "id":436,
            "name":"四、坚持走中国式现代化新道路",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-0-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":13267,
            "read_info":{

            }
        },
        {
            "id":437,
            "name":"第二节以改革开放引领经济发展新常态",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":12562,
            "read_info":{

            }
        },
        {
            "id":438,
            "name":"一、科学把握经济形势新变化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-1-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":12686,
            "read_info":{

            }
        },
        {
            "id":439,
            "name":"二、坚持稳中求进的工作总基调",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-1-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":12140,
            "read_info":{

            }
        },
        {
            "id":440,
            "name":"三、以供给侧结构性改革为主线",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-1-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":16634,
            "read_info":{

            }
        },
        {
            "id":441,
            "name":"四、坚持全面深化改革",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-1-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":15334,
            "read_info":{

            }
        },
        {
            "id":442,
            "name":"五、扩大高水平对外开放",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-1-4.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":10964,
            "read_info":{

            }
        },
        {
            "id":443,
            "name":"第三节以新发展理念引领高质量发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":10482,
            "read_info":{

            }
        },
        {
            "id":444,
            "name":"一、提出并确立新发展理念",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-2-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":10602,
            "read_info":{

            }
        },
        {
            "id":445,
            "name":"二、建设现代化经济体系",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-2-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":10293,
            "read_info":{

            }
        },
        {
            "id":446,
            "name":"三、坚持和完善中国特色社会主义基本经济制度",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-2-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":10070,
            "read_info":{

            }
        },
        {
            "id":447,
            "name":"四、部署实施国家重大发展战略",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-2-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":9716,
            "read_info":{

            }
        },
        {
            "id":448,
            "name":"五、大力发展制造业和实体经济",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-2-4.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":9429,
            "read_info":{

            }
        },
        {
            "id":449,
            "name":"第四节规划新蓝图，开启新阶段",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":9125,
            "read_info":{

            }
        },
        {
            "id":450,
            "name":"一、规划“两个一百年”奋斗目标的蓝图",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-3-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":9217,
            "read_info":{

            }
        },
        {
            "id":451,
            "name":"二、把握新发展阶段，贯彻新发展理念，构建新发展格局",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-3-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":8996,
            "read_info":{

            }
        },
        {
            "id":452,
            "name":"三、扎实推动共同富裕",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-3-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":8661,
            "read_info":{

            }
        },
        {
            "id":453,
            "name":"四、统筹好发展和安全两件大事",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-3-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":8424,
            "read_info":{

            }
        },
        {
            "id":454,
            "name":"第二章 充分发挥市场的决定作用",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-3-3_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":8288,
            "read_info":{

            }
        },
        {
            "id":455,
            "name":"第一节激发各类市场主体活力",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-4.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":8090,
            "read_info":{

            }
        },
        {
            "id":456,
            "name":"一、对政府和市场关系的新认识",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-4-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":8119,
            "read_info":{

            }
        },
        {
            "id":457,
            "name":"二、市场主体的新变化与“两个毫不动摇”",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-4-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":8091,
            "read_info":{

            }
        },
        {
            "id":458,
            "name":"三、健全反垄断措施和防范资本无序扩张",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-4-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":7697,
            "read_info":{

            }
        },
        {
            "id":459,
            "name":"第二节建设高水平社会主义市场经济体制",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-5.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":7447,
            "read_info":{

            }
        },
        {
            "id":460,
            "name":"一、推行负面清单制度",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-5-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":7545,
            "read_info":{

            }
        },
        {
            "id":461,
            "name":"二、工商登记便利化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-5-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":7338,
            "read_info":{

            }
        },
        {
            "id":462,
            "name":"三、完善市场定价机制",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-5-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":7326,
            "read_info":{

            }
        },
        {
            "id":463,
            "name":"第三节完善现代市场管理体系和制度",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-6.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6938,
            "read_info":{

            }
        },
        {
            "id":464,
            "name":"一、改革市场监管体制",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-6-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6962,
            "read_info":{

            }
        },
        {
            "id":465,
            "name":"二、完善市场监管体系",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-6-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6854,
            "read_info":{

            }
        },
        {
            "id":466,
            "name":"三、健全社会信用体系",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-6-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6736,
            "read_info":{

            }
        },
        {
            "id":467,
            "name":"第三章 更好发挥党和政府作用",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-6-2_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6649,
            "read_info":{

            }
        },
        {
            "id":468,
            "name":"第一节加强党对经济工作的领导",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-7.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6568,
            "read_info":{

            }
        },
        {
            "id":469,
            "name":"一、完善党领导经济工作的制度建设",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-7-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6587,
            "read_info":{

            }
        },
        {
            "id":470,
            "name":"二、强化党对经济领域重大工作的战略部署",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-7-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6525,
            "read_info":{

            }
        },
        {
            "id":471,
            "name":"三、加强党对全面深化经济体制改革的统筹领导",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-7-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6433,
            "read_info":{

            }
        },
        {
            "id":472,
            "name":"四、坚持党对国有企业的领导",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-7-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6411,
            "read_info":{

            }
        },
        {
            "id":473,
            "name":"第二节政府职能的积极转变",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-8.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6250,
            "read_info":{

            }
        },
        {
            "id":474,
            "name":"一、政府经济机构改革稳步推进",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-8-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6318,
            "read_info":{

            }
        },
        {
            "id":475,
            "name":"二、“放管服”改革持续推进",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-8-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6161,
            "read_info":{

            }
        },
        {
            "id":476,
            "name":"三、数字政府与服务型政府相互融通",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-8-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6102,
            "read_info":{

            }
        },
        {
            "id":477,
            "name":"第三节宏观调控体系的创新完善",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-9.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6005,
            "read_info":{

            }
        },
        {
            "id":478,
            "name":"一、区间调控、定向调控与微刺激政策的有机结合",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-9-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6056,
            "read_info":{

            }
        },
        {
            "id":479,
            "name":"二、供给管理与需求管理双向发力",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-9-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6021,
            "read_info":{

            }
        },
        {
            "id":480,
            "name":"三、加大房地产市场调控力度",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-9-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5939,
            "read_info":{

            }
        },
        {
            "id":481,
            "name":"第四节中长期规划效能的不断提升",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-10.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5834,
            "read_info":{

            }
        },
        {
            "id":482,
            "name":"一、国家规划总揽经济高质量发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-10-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5897,
            "read_info":{

            }
        },
        {
            "id":483,
            "name":"二、产业规划推动现代产业体系建设",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-10-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5784,
            "read_info":{

            }
        },
        {
            "id":484,
            "name":"三、科技规划激活大国经济发展新动能",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-10-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5765,
            "read_info":{

            }
        },
        {
            "id":485,
            "name":"第四章加快农业农村现代化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-10-2_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5666,
            "read_info":{

            }
        },
        {
            "id":486,
            "name":"第一节优先发展农业农村",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-11.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5613,
            "read_info":{

            }
        },
        {
            "id":487,
            "name":"一、加强党对“三农”工作的全面领导",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-11-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5631,
            "read_info":{

            }
        },
        {
            "id":488,
            "name":"二、坚持农业农村优先发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-11-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5542,
            "read_info":{

            }
        },
        {
            "id":489,
            "name":"三、推进农业供给侧结构性改革",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-11-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5486,
            "read_info":{

            }
        },
        {
            "id":490,
            "name":"四、积极推进农业农村现代化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-11-2.xhtml#AUTO_ID_1",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5476,
            "read_info":{

            }
        },
        {
            "id":491,
            "name":"第二节全面推进乡村振兴",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-12.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5369,
            "read_info":{

            }
        },
        {
            "id":492,
            "name":"一、乡村振兴战略的提出",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-12-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5367,
            "read_info":{

            }
        },
        {
            "id":493,
            "name":"二、制定和实施乡村振兴战略规划和乡村振兴促进法",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-12-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5297,
            "read_info":{

            }
        },
        {
            "id":494,
            "name":"三、乡村振兴扎实推进",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-12-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5247,
            "read_info":{

            }
        },
        {
            "id":495,
            "name":"第三节农村经营主体创新发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-13.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5149,
            "read_info":{

            }
        },
        {
            "id":496,
            "name":"一、农村集体土地“三权分置”改革",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-13-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5142,
            "read_info":{

            }
        },
        {
            "id":497,
            "name":"二、推进农村集体产权制度改革",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-13-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5120,
            "read_info":{

            }
        },
        {
            "id":498,
            "name":"三、促进小农户和现代农业发展有机衔接",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-13-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5083,
            "read_info":{

            }
        },
        {
            "id":499,
            "name":"第五章 从工业大国迈向工业强国",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-13-2_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5064,
            "read_info":{

            }
        },
        {
            "id":500,
            "name":"第一节世界第一工业大国的新征程",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-14.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5030,
            "read_info":{

            }
        },
        {
            "id":501,
            "name":"一、三期叠加与新科技革命",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-14-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5089,
            "read_info":{

            }
        },
        {
            "id":502,
            "name":"二、国家发展规划的战略导向",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-14-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":5011,
            "read_info":{

            }
        },
        {
            "id":503,
            "name":"三、工业转向高质量发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-14-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4979,
            "read_info":{

            }
        },
        {
            "id":504,
            "name":"第二节创新驱动开辟新局面",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-15.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4904,
            "read_info":{

            }
        },
        {
            "id":505,
            "name":"一、企业自主创新",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-15-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4921,
            "read_info":{

            }
        },
        {
            "id":506,
            "name":"二、大力推动工业创新发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-15-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4926,
            "read_info":{

            }
        },
        {
            "id":507,
            "name":"三、专精特新企业发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-15-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4844,
            "read_info":{

            }
        },
        {
            "id":508,
            "name":"四、军民融合释放活力",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-15-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4795,
            "read_info":{

            }
        },
        {
            "id":509,
            "name":"第三节向制造业强国大步迈进",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-16.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4755,
            "read_info":{

            }
        },
        {
            "id":510,
            "name":"一、工业门类齐全与结构不断优化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-16-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4805,
            "read_info":{

            }
        },
        {
            "id":511,
            "name":"二、工业区域布局优化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-16-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4735,
            "read_info":{

            }
        },
        {
            "id":512,
            "name":"三、中国工业在全球经济中的地位提升",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-16-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4722,
            "read_info":{

            }
        },
        {
            "id":513,
            "name":"四、中国工业的标志性成就",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-16-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4710,
            "read_info":{

            }
        },
        {
            "id":514,
            "name":"第六章 突飞猛进的交通事业",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-16-3_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4693,
            "read_info":{

            }
        },
        {
            "id":515,
            "name":"第一节交通发展的动力和规划",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-17.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4620,
            "read_info":{

            }
        },
        {
            "id":516,
            "name":"一、交通大发展的机遇和条件",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-17-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4648,
            "read_info":{

            }
        },
        {
            "id":517,
            "name":"二、全行业发展规划纷纷出台",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-17-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4667,
            "read_info":{

            }
        },
        {
            "id":518,
            "name":"三、交通投融资改革动力强劲",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-17-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4629,
            "read_info":{

            }
        },
        {
            "id":519,
            "name":"四、城市公共交通方兴未艾",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-17-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4571,
            "read_info":{

            }
        },
        {
            "id":520,
            "name":"第二节交通发展规划稳步实施",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-18.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4503,
            "read_info":{

            }
        },
        {
            "id":521,
            "name":"一、交通基建能力震惊世界",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-18-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4529,
            "read_info":{

            }
        },
        {
            "id":522,
            "name":"二、交通改善取得历史性成就",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-18-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4486,
            "read_info":{

            }
        },
        {
            "id":523,
            "name":"三、全面对接“一带一路”",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-18-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4452,
            "read_info":{

            }
        },
        {
            "id":524,
            "name":"第三节交通发展成效显著",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-19.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4407,
            "read_info":{

            }
        },
        {
            "id":525,
            "name":"一、装备技术进步全球瞩目",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-19-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4429,
            "read_info":{

            }
        },
        {
            "id":526,
            "name":"二、交通管理现代化能力加强",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-19-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4399,
            "read_info":{

            }
        },
        {
            "id":527,
            "name":"三、交通强国战略部署有序推进",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-19-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4370,
            "read_info":{

            }
        },
        {
            "id":528,
            "name":"第七章 充满活力的商贸物流",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-19-2_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4396,
            "read_info":{

            }
        },
        {
            "id":529,
            "name":"第一节商贸物流转型发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-20.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4343,
            "read_info":{

            }
        },
        {
            "id":530,
            "name":"一、科技革命推动传统商贸转型",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-20-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4362,
            "read_info":{

            }
        },
        {
            "id":531,
            "name":"二、空前活跃的新业态",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-20-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4351,
            "read_info":{

            }
        },
        {
            "id":532,
            "name":"三、商贸实力稳步增强",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-20-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4303,
            "read_info":{

            }
        },
        {
            "id":533,
            "name":"四、商贸发展渐趋规范",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-20-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4273,
            "read_info":{

            }
        },
        {
            "id":534,
            "name":"第二节商贸物流服务业的创新",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-21.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4214,
            "read_info":{

            }
        },
        {
            "id":535,
            "name":"一、供应链物流",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-21-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4246,
            "read_info":{

            }
        },
        {
            "id":536,
            "name":"二、智慧物流",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-21-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4214,
            "read_info":{

            }
        },
        {
            "id":537,
            "name":"三、新型服务业的繁荣",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-21-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4198,
            "read_info":{

            }
        },
        {
            "id":538,
            "name":"第三节商贸物流新态势",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-22.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4166,
            "read_info":{

            }
        },
        {
            "id":539,
            "name":"一、商贸物流通区域",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-22-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4206,
            "read_info":{

            }
        },
        {
            "id":540,
            "name":"二、商贸物流联天下",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-22-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4188,
            "read_info":{

            }
        },
        {
            "id":541,
            "name":"三、网购和快递带来消费方式的变化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-22-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4176,
            "read_info":{

            }
        },
        {
            "id":542,
            "name":"第八章 发展与安全并重的金融",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-22-2_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4185,
            "read_info":{

            }
        },
        {
            "id":543,
            "name":"第一节金融实现飞跃发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-23.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4146,
            "read_info":{

            }
        },
        {
            "id":544,
            "name":"一、金融实力空前增强",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-23-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4191,
            "read_info":{

            }
        },
        {
            "id":545,
            "name":"二、货币政策不断完善",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-23-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4124,
            "read_info":{

            }
        },
        {
            "id":546,
            "name":"三、金融质量大幅改善",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-23-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4094,
            "read_info":{

            }
        },
        {
            "id":547,
            "name":"第二节开展金融创新和维护金融安全",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-24.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4058,
            "read_info":{

            }
        },
        {
            "id":548,
            "name":"一、加强党对金融的全面领导",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-24-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4079,
            "read_info":{

            }
        },
        {
            "id":549,
            "name":"二、金融创新和金融监管",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-24-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4108,
            "read_info":{

            }
        },
        {
            "id":550,
            "name":"三、培育并规制资本市场",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-24-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4048,
            "read_info":{

            }
        },
        {
            "id":551,
            "name":"四、央行数字货币",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-24-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4018,
            "read_info":{

            }
        },
        {
            "id":552,
            "name":"第三节普惠金融高质量发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-25.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4044,
            "read_info":{

            }
        },
        {
            "id":553,
            "name":"一、金融组织的普惠体系",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-25-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4048,
            "read_info":{

            }
        },
        {
            "id":554,
            "name":"二、金融市场的普惠体系",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-25-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4039,
            "read_info":{

            }
        },
        {
            "id":555,
            "name":"三、对小微企业的积极扶持",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-25-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4026,
            "read_info":{

            }
        },
        {
            "id":556,
            "name":"第四节金融开放",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-26.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4009,
            "read_info":{

            }
        },
        {
            "id":557,
            "name":"一、央行的对外交流与合作",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-26-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4014,
            "read_info":{

            }
        },
        {
            "id":558,
            "name":"二、金融的扩大开放",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-26-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3995,
            "read_info":{

            }
        },
        {
            "id":559,
            "name":"三、积极推进人民币国际化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-26-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3993,
            "read_info":{

            }
        },
        {
            "id":560,
            "name":"第九章 建立健全现代财税体制",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-26-2_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3964,
            "read_info":{

            }
        },
        {
            "id":561,
            "name":"第一节积极的财政政策和改革预算管理",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-27.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3926,
            "read_info":{

            }
        },
        {
            "id":562,
            "name":"一、落实新发展理念的积极财政政策",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-27-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3943,
            "read_info":{

            }
        },
        {
            "id":563,
            "name":"二、《中华人民共和国预算法》的修正",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-27-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3923,
            "read_info":{

            }
        },
        {
            "id":564,
            "name":"三、全面实施预算绩效管理",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-27-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3902,
            "read_info":{

            }
        },
        {
            "id":565,
            "name":"第二节税收制度的发展和完善",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-28.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3869,
            "read_info":{

            }
        },
        {
            "id":566,
            "name":"一、全面推进营改增改革",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-28-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3900,
            "read_info":{

            }
        },
        {
            "id":567,
            "name":"二、改进税收征管办法",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-28-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3867,
            "read_info":{

            }
        },
        {
            "id":568,
            "name":"三、完善地方税体系",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-28-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3867,
            "read_info":{

            }
        },
        {
            "id":569,
            "name":"四、税收政策支持社会经济发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-28-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3884,
            "read_info":{

            }
        },
        {
            "id":570,
            "name":"第三节中央和地方财政关系的调整",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-29.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3814,
            "read_info":{

            }
        },
        {
            "id":571,
            "name":"一、央地财事平衡的新探索",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-29-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3852,
            "read_info":{

            }
        },
        {
            "id":572,
            "name":"二、完善转移支付制度",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-29-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3840,
            "read_info":{

            }
        },
        {
            "id":573,
            "name":"三、加强地方债务管理",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-29-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3823,
            "read_info":{

            }
        },
        {
            "id":574,
            "name":"第四节 充分发挥财政在高质量发展和普惠民生中的作用",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-30.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3796,
            "read_info":{

            }
        },
        {
            "id":575,
            "name":"一、财政收支总量和结构的变化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-30-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3811,
            "read_info":{

            }
        },
        {
            "id":576,
            "name":"二、持续保障和改善民生",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-30-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3814,
            "read_info":{

            }
        },
        {
            "id":577,
            "name":"三、改善二次分配调节居民收入",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-30-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3790,
            "read_info":{

            }
        },
        {
            "id":578,
            "name":"四、公共服务供给的均等化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-30-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3768,
            "read_info":{

            }
        },
        {
            "id":579,
            "name":"第十章 加强区域城乡协调发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-30-3_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3773,
            "read_info":{

            }
        },
        {
            "id":580,
            "name":"第一节开创区域经济统筹协调发展的新格局",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-31.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3740,
            "read_info":{

            }
        },
        {
            "id":581,
            "name":"一、区域协调发展战略的新布局",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-31-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3768,
            "read_info":{

            }
        },
        {
            "id":582,
            "name":"二、城市群都市圈建设取得新突破",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-31-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3743,
            "read_info":{

            }
        },
        {
            "id":583,
            "name":"三、区域一体化取得新进展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-31-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3719,
            "read_info":{

            }
        },
        {
            "id":584,
            "name":"第二节区域协调发展机制的新探索",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-32.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3681,
            "read_info":{

            }
        },
        {
            "id":585,
            "name":"一、深化区域合作机制",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-32-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3697,
            "read_info":{

            }
        },
        {
            "id":586,
            "name":"二、优化区域互助机制",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-32-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3710,
            "read_info":{

            }
        },
        {
            "id":587,
            "name":"三、健全区际利益补偿机制",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-32-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3691,
            "read_info":{

            }
        },
        {
            "id":588,
            "name":"第三节协调城乡发展与城镇化快速推进",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-33.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3645,
            "read_info":{

            }
        },
        {
            "id":589,
            "name":"一、促进城乡协调发展的政策和措施",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-33-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3680,
            "read_info":{

            }
        },
        {
            "id":590,
            "name":"二、城乡融合发展的新进展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-33-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3666,
            "read_info":{

            }
        },
        {
            "id":591,
            "name":"三、城镇化的快速推进",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-33-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3673,
            "read_info":{

            }
        },
        {
            "id":592,
            "name":"第十一章 贯彻生态文明建设新理念",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-33-2_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3674,
            "read_info":{

            }
        },
        {
            "id":593,
            "name":"第一节绿水青山就是金山银山",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-34.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3630,
            "read_info":{

            }
        },
        {
            "id":594,
            "name":"一、贯彻“绿水青山就是金山银山”理念",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-34-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3624,
            "read_info":{

            }
        },
        {
            "id":595,
            "name":"二、构建生态文明制度体系",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-34-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3598,
            "read_info":{

            }
        },
        {
            "id":596,
            "name":"三、打赢污染防治攻坚战",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-34-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3581,
            "read_info":{

            }
        },
        {
            "id":597,
            "name":"第二节坚持绿色可持续发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-35.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3578,
            "read_info":{

            }
        },
        {
            "id":598,
            "name":"一、压缩并淘汰“三高”产能",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-35-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3594,
            "read_info":{

            }
        },
        {
            "id":599,
            "name":"二、积极开发新能源",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-35-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3586,
            "read_info":{

            }
        },
        {
            "id":600,
            "name":"三、大力推进低碳经济发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-35-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3550,
            "read_info":{

            }
        },
        {
            "id":601,
            "name":"四、循环经济的新发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-35-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3565,
            "read_info":{

            }
        },
        {
            "id":602,
            "name":"第三节积极参与和推进全球绿色发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-36.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3540,
            "read_info":{

            }
        },
        {
            "id":603,
            "name":"一、倡导共谋全球生态文明建设之路",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-36-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3531,
            "read_info":{

            }
        },
        {
            "id":604,
            "name":"二、积极推进全球环境治理合作",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-36-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3533,
            "read_info":{

            }
        },
        {
            "id":605,
            "name":"三、稳步推进碳达峰和碳中和",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-36-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3516,
            "read_info":{

            }
        },
        {
            "id":606,
            "name":"第十二章 消除贫困和共享发展成果",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-36-2_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3542,
            "read_info":{

            }
        },
        {
            "id":607,
            "name":"第一节创造人类减贫史上的奇迹",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-37.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3515,
            "read_info":{

            }
        },
        {
            "id":608,
            "name":"一、全体人民的小康",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-37-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3523,
            "read_info":{

            }
        },
        {
            "id":609,
            "name":"二、贯彻实施精准扶贫",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-37-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3500,
            "read_info":{

            }
        },
        {
            "id":610,
            "name":"三、打赢脱贫攻坚战",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-37-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3501,
            "read_info":{

            }
        },
        {
            "id":611,
            "name":"四、解决困扰千年的绝对贫困",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-37-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3519,
            "read_info":{

            }
        },
        {
            "id":612,
            "name":"第二节统筹疫情防控和经济社会发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-38.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3478,
            "read_info":{

            }
        },
        {
            "id":613,
            "name":"一、打响疫情防控的人民战争",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-38-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3495,
            "read_info":{

            }
        },
        {
            "id":614,
            "name":"二、率先恢复经济社会发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-38-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3488,
            "read_info":{

            }
        },
        {
            "id":615,
            "name":"三、构建人类卫生健康共同体",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-38-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3483,
            "read_info":{

            }
        },
        {
            "id":616,
            "name":"第三节体现效率促进公平的收人分配体系",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-39.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3458,
            "read_info":{

            }
        },
        {
            "id":617,
            "name":"一、推动实现更加充分、更高质量的就业",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-39-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3483,
            "read_info":{

            }
        },
        {
            "id":618,
            "name":"二、促进收入分配更合理、更有序",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-39-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3469,
            "read_info":{

            }
        },
        {
            "id":619,
            "name":"三、创造人民高品质美好生活",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-39-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3466,
            "read_info":{

            }
        },
        {
            "id":620,
            "name":"四、扎实推进共同富裕",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-39-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3473,
            "read_info":{

            }
        },
        {
            "id":621,
            "name":"第四节在高质量发展中改善和保障民生",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-40.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3443,
            "read_info":{

            }
        },
        {
            "id":622,
            "name":"一、办好人民满意的教育",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-40-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3436,
            "read_info":{

            }
        },
        {
            "id":623,
            "name":"二、推进基本公共服务均等化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-40-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3446,
            "read_info":{

            }
        },
        {
            "id":624,
            "name":"三、健全多层次社会保障体系",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-40-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3450,
            "read_info":{

            }
        },
        {
            "id":625,
            "name":"四、全面推进健康中国建设",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-40-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3435,
            "read_info":{

            }
        },
        {
            "id":626,
            "name":"第五节创造社会长期稳定的奇迹",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-41.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3413,
            "read_info":{

            }
        },
        {
            "id":627,
            "name":"一、统筹发展和安全两件大事",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-41-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3431,
            "read_info":{

            }
        },
        {
            "id":628,
            "name":"二、建设更高水平的平安中国",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-41-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3414,
            "read_info":{

            }
        },
        {
            "id":629,
            "name":"三、共建共治共享社会治理",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-41-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3418,
            "read_info":{

            }
        },
        {
            "id":630,
            "name":"四、完善健全公共安全体系",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-41-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3443,
            "read_info":{

            }
        },
        {
            "id":631,
            "name":"第十三章 扩大对外开放与合作共赢",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-41-3_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3426,
            "read_info":{

            }
        },
        {
            "id":632,
            "name":"第一节应对百年未有之大变局",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-42.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3384,
            "read_info":{

            }
        },
        {
            "id":633,
            "name":"一、世界处于百年未有之大变局",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-42-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3406,
            "read_info":{

            }
        },
        {
            "id":634,
            "name":"二、推动构建人类命运共同体",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-42-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3414,
            "read_info":{

            }
        },
        {
            "id":635,
            "name":"三、积极发展全球伙伴关系",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-42-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3433,
            "read_info":{

            }
        },
        {
            "id":636,
            "name":"四、参与全球经济治理体系改革和建设",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-42-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3422,
            "read_info":{

            }
        },
        {
            "id":637,
            "name":"第二节推进合作共赢的经济全球化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-43.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3383,
            "read_info":{

            }
        },
        {
            "id":638,
            "name":"一、参与和推动世贸组织改革进程",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-43-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3397,
            "read_info":{

            }
        },
        {
            "id":639,
            "name":"二、货物贸易第一大国地位稳固",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-43-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3394,
            "read_info":{

            }
        },
        {
            "id":640,
            "name":"三、贸易结构持续优化",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-43-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3400,
            "read_info":{

            }
        },
        {
            "id":641,
            "name":"四、对外经济援助展现大国担当、取得新的重大成就",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-43-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3395,
            "read_info":{

            }
        },
        {
            "id":642,
            "name":"第三节推动共建“一带一路”和对外直接投资高质量发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-44.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3390,
            "read_info":{

            }
        },
        {
            "id":643,
            "name":"一、共建“一带一路”",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-44-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3425,
            "read_info":{

            }
        },
        {
            "id":644,
            "name":"二、“走出去”体制机制和政策体系进一步完善",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-44-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3412,
            "read_info":{

            }
        },
        {
            "id":645,
            "name":"三、对外直接投资高质量发展",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-44-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3448,
            "read_info":{

            }
        },
        {
            "id":646,
            "name":"四、与东道国合作共赢效果显著",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-44-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3449,
            "read_info":{

            }
        },
        {
            "id":647,
            "name":"第四节全面构建高水平对外开放新格局",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-45.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3476,
            "read_info":{

            }
        },
        {
            "id":648,
            "name":"一、构筑高水平对外开放新优势",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-45-0.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3562,
            "read_info":{

            }
        },
        {
            "id":649,
            "name":"二、推动完善外商投资准入负面清单",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-45-1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3558,
            "read_info":{

            }
        },
        {
            "id":650,
            "name":"三、全球引资大国地位更加巩固",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-45-2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3658,
            "read_info":{

            }
        },
        {
            "id":651,
            "name":"四、引资规模和质量“双提升”",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-45-3.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3779,
            "read_info":{

            }
        },
        {
            "id":652,
            "name":"结束语",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter0-45-3_0001.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":3941,
            "read_info":{

            }
        },
        {
            "id":653,
            "name":"主要参考文献",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter1.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":4796,
            "read_info":{
                "last_update_sign":""
            }
        },
        {
            "id":654,
            "name":"后记",
            "toc_href":"\/epub\/86828969\/OEBPS\/Text\/chapter2.xhtml",
            "audio":"",
            "duration":"0.00",
            "broadcast_num":6605,
            "read_info":{
                "last_update_sign":"\/epub\/86828969\/OEBPS\/Text\/chapter2.xhtml"
            }
        }
    ],
    "code":1000,
    "done":true
}
"""
